name: movie_mate
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  device_info_plus: ^11.3.3
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_spinkit: ^5.2.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.1
  lottie: ^3.3.1
  share_plus: ^10.1.4
  sqflite: ^2.4.2
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/plus.png
    - assets/images/movie_bg.png
    - assets/images/user_avatar.png
    - assets/images/placeholder.jpg
    - assets/images/splash_logo.png
    - assets/empty.json
    - assets/images/movie.png

flutter_native_splash:
  color: "#B85042" # Background color
  android_12:
    background_image: assets/cinema.png
    android_gravity: center

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
